### PR TITLE
Add AusweisApp2 1.8.0 as eid-de

### PR DESCRIPTION
**Pull request by lunaryorn**
Electronic identity card software for Germany, follow up to https://github.com/caskroom/homebrew-cask/pull/24116

#### Adding a new cask

- [x] Checked there aren’t open [pull requests](https://github.com/caskroom/homebrew-eid/pulls) for the same cask.
- [x] Checked there aren’t closed [issues](https://github.com/caskroom/homebrew-eid/issues) where that cask was already refused.
- [x] Cask’s token follows the `eid-{{country_code}}` pattern.
- [x] Commit message includes cask’s name.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by lunaryorn** [comment]
Anyone?

**Comment by adidalal** [comment]
Unfortunately I don't have merge privileges in this repo

**Comment by vitorgalvao** [comment]
> Unfortunately I don't have merge privileges in this repo

Clearly an oversight (this repo wasn’t added to the team yet). Fixed now.

**Pull request merged**
