### PR TITLE
squiggly heredocs

### PR DESCRIPTION
**Pull request by commitay**
~~On hold.~~

https://github.com/caskroom/homebrew-cask/pull/39869

### CODE REVIEW

**Comment by reitermarkus** [comment]
> On hold.

There's no reason to.

**Comment by commitay** [comment]
`style` doesn't seem to like the `~` when I run it locally.

**Comment by reitermarkus** [comment]
Ah, ok, `rubocop-cask` needs to be updated then.

**Comment by commitay** [comment]
This passes `style` now. I've made the "squiggly" changes to all of the other repos, I'll open PRs for them.

**Pull request merged**
